# Generated by Django 3.1.6 on 2021-02-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(choices=[('Jamon', 'Jamon'), ('Champiñon', 'Champiñon'), ('Pimentón', 'Pimentón'), ('Doble Queso', 'Doble Queso'), ('Aceitunas', 'Aceitunas'), ('Pepperoni', 'Pepperoni'), ('Salchichón', 'Salchichón')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField()),
                ('tamaño', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_Ing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ingredientes')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='adicionales',
            field=models.ManyToManyField(through='tienda.Pizza_Ing', to='tienda.Ingredientes'),
        ),
        migrations.CreateModel(
            name='Pedido_Pizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pizzas',
            field=models.ManyToManyField(through='tienda.Pedido_Pizzas', to='tienda.Pizza'),
        ),
    ]
