# Generated by Django 3.1.6 on 2021-02-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', through='tienda.Pedido_Pizzas', to='tienda.Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='adicionales',
            field=models.ManyToManyField(related_name='adicionales', through='tienda.Pizza_Ing', to='tienda.Ingredientes'),
        ),
    ]
